#ifndef FILE_priorities_SEEN
#define FILE_priorities_SEEN

// large number = high priority
#define PRIORITY_WAVE_ROW_SERVICE 10
#define PRIORITY_SYNC_TIME_SERVICE_HYPED 9
#define PRIORITY_UDP_RECEIVER 8
#define PRIORITY_TCP_RECEIVER 7
#define PRIORITY_FINGERS 6
#define PRIORITY_PRESSURE 5
#define PRIORITY_SYNTH_SERVICE 4
#define PRIORITY_AUTO_POF_SERVICE 4
#define PRIORITY_RELAY_RESIDUAL_PRESSURE 3
#define PRIORITY_INIT_COMM_CHANNEL 2
#define PRIORITY_INIT_LOCAL_FEATURES 2
#define PRIORITY_DETACH 2
#define PRIORITY_AMPLITUDE_DECAY 2
#define PRIORITY_SYNC_TIME_SERVICE_CHILL 1
#define PRIORITY_JINGLE 1
#define PRIORITY_BATTERY_SERVICE_BURST 1
#define PRIORITY_BATTERY_SERVICE_CHILL 1

#endif
